version: '2.1'

services:
  my_app:
    image: my_app
    volumes:
      - .:/usr/src/app
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=testNewBoilerplate